---
title: "CENSUS2020 - Propencity to Participate Explorer -Draft V0.1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(leaflet)
library(leaflet.extras)
library(plotly)
library(DT)
library(sf)
library(dplyr)
library(tidyr)
library(tidyselect)
library(ggplot2)

df_1 <- readRDS("data/df_1.rds")
df_fin <- readRDS("data/df_fin.rds")

sd1 <- SharedData$new(df_1)
sd2 <- SharedData$new(df_fin %>% select(-popup_text))
```

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r selectors}
filter_slider("rspns_score", "Propensity", sd2, ~rspns_score,  step = 1)
filter_select("tarct", "Select Tract by number: ex 002102", sd2, ~tract)
filter_checkbox("block_group", "Block Group", sd2, ~block_group, inline = TRUE) 
```
  
Column {.tabset .tabset-fade}
-------------------------------------
 
### DC Tract and Block Group 

```{r LeafLetMap_1}

pal <- colorNumeric(palette = "Reds",
                    domain = df_fin$rspns_score)

dc_leaf <- leaflet(df_fin) %>%
               addProviderTiles("CartoDB.DarkMatter") %>%
               setView(lng = -77.03687, lat = 38.90717, zoom = 12) %>%
               addResetMapButton() %>%
               addPolygons(data = sd1,
                          color = "#333333", ##444444", 
                           dashArray = "3",
                           weight = 2,   #line thickness 
                           smoothFactor = 0.5,
                           opacity = 0.5,
                           fillOpacity = 0.8,
                           highlightOptions = highlightOptions(color = "green", weight = 4,bringToFront = TRUE), 
                           popup = df_fin$popup_text,
                           label = ~trct_blk
                           ) %>% 
              addLegend( position = "bottomleft", 
                              pal = pal, 
                              values = ~rspns_score,
                              title = "Propensity",
                              opacity = .8
                              ) %>%
              addPolylines(data = sd1 ,
                                stroke = TRUE, 
                                smoothFactor = 1,
                                weight = 1, 
                                color = "gray"
                           ) %>% 
              addCircleMarkers(data = sd2,
                               radius = .001, 
                               color = ~pal(df_1$rspns_score),
                               group = "BlockGroup"
                               )
       
dc_leaf
```

### Tab 2 

### Tab 3


Column {data-width=400}
-------------------------------------
   
### Language

```{r dataTable_1}
library(DT)
datatable(sd2, rownames = TRUE, extensions = 'Scroller', options = list(
  scrollY = 200,
  scroller = TRUE
))
```   
 
### Propensity Index
    
```{r scorePlot_1}
library(plotly)
p2 <- plot_ly(sd2, x = ~mail_return, y = ~rspns_score) %>%  
        add_markers() 
p2
```
